# -*- coding: utf-8 -*-
"""Finalmodels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1gxNti1B79-yI3zIL6eWm3cjsOCDL5u
"""

import os
import cv2
import numpy as np

import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB5
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D, BatchNormalization, LayerNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.applications.efficientnet import preprocess_input
from sklearn.utils.class_weight import compute_class_weight

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

dataset_path = "/content/drive/MyDrive/Dataset"

# Padding and Resizing Function
def pad_and_resize(img, target_size=(456, 456)):
    h, w = img.shape[:2]
    max_dim = max(h, w)
    top = (max_dim - h) // 2
    bottom = max_dim - h - top
    left = (max_dim - w) // 2
    right = max_dim - w - left
    img_padded = cv2.copyMakeBorder(img, top, bottom, left, right, cv2.BORDER_CONSTANT, value=[255, 255, 255])
    img_resized = cv2.resize(img_padded, target_size)
    return preprocess_input(img_resized.astype(np.float32))

# Enhanced Data Augmentation
aug_gen = ImageDataGenerator(
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    brightness_range=[0.8, 1.2],    # Added brightness adjustment
    channel_shift_range=10.0,       # Enhanced contrast
    fill_mode="nearest"
)

# Load images
X, y, labels = [], [], []
class_names = sorted(os.listdir(dataset_path))

for class_index, class_name in enumerate(class_names):
    class_path = os.path.join(dataset_path, class_name)
    if os.path.isdir(class_path):
        for img_name in os.listdir(class_path):
            img_path = os.path.join(class_path, img_name)
            img = cv2.imread(img_path)
            if img is not None:
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                img = pad_and_resize(img)
                X.append(img)
                y.append(class_index)
                labels.append(class_name)

X = np.array(X, dtype=np.float32)
y = np.array(y)
y = to_categorical(y, num_classes=len(class_names))

# Compute Class Weights
class_weights = compute_class_weight("balanced", classes=np.unique(y.argmax(axis=1)), y=y.argmax(axis=1))
class_weights = {i: weight for i, weight in enumerate(class_weights)}

# Augment Dataset
augmented_images, augmented_labels = [], []
for i in range(len(X)):
    img = X[i].reshape((1,) + X[i].shape)
    label = y[i]
    count = 0
    for batch in aug_gen.flow(img, batch_size=1):
        augmented_images.append(batch[0])
        augmented_labels.append(label)
        count += 1
        if count >= 4:  # Increased augmentation samples per image
            break

X_aug = np.array(augmented_images, dtype=np.float32)
y_aug = np.array(augmented_labels)

# Combine Original and Augmented Data
X_combined = np.concatenate((X, X_aug), axis=0)
y_combined = np.concatenate((y, y_aug), axis=0)

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X_combined, y_combined, test_size=0.2, random_state=42)

# Load EfficientNetB5
base_model = EfficientNetB5(weights="imagenet", include_top=False, input_shape=(456, 456, 3))

# Freeze Pretrained Layers Initially
for layer in base_model.layers:
    layer.trainable = False

# Model Architecture
x = GlobalAveragePooling2D()(base_model.output)
x = BatchNormalization()(x)
x = LayerNormalization()(x)   # Added Layer Normalization
x = Dense(512, activation="relu")(x)  # Increased neurons for better learning capacity
x = Dropout(0.4)(x)
x = Dense(256, activation="relu")(x)
x = Dropout(0.5)(x)
output = Dense(len(class_names), activation="softmax")(x)

model = Model(inputs=base_model.input, outputs=output)
model.compile(optimizer=Adam(learning_rate=1e-4), loss="categorical_crossentropy", metrics=["accuracy"])

# Callbacks
callbacks = [
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=4, min_lr=1e-6, verbose=1),
    EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True, verbose=1)
]

# Train Model
history = model.fit(
    X_train, y_train,
    epochs=35,  # Increased epochs for better learning
    batch_size=16,  # Reduced batch size for improved convergence
    validation_data=(X_test, y_test),
    class_weight=class_weights,
    callbacks=callbacks
)


# Prediction Function
def predict_shade(image_path):
    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = pad_and_resize(img)
    img = np.expand_dims(img, axis=0)
    prediction = model.predict(img)
    predicted_class = class_names[np.argmax(prediction)]
    print(f"Predicted Shade: {predicted_class}")
    return predicted_class

# Test Prediction
test_image_path = "/content/drive/MyDrive/Dataset/4M_1/4.jpg"
predicted_shade = predict_shade(test_image_path)

import os
import cv2
import numpy as np

import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50  # Using ResNet50 instead of EfficientNetB5
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D, BatchNormalization, LayerNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.applications.resnet50 import preprocess_input  # Preprocessing for ResNet50
from sklearn.utils.class_weight import compute_class_weight

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

dataset_path = "/content/drive/MyDrive/Dataset"

# Padding and Resizing Function
def pad_and_resize(img, target_size=(224, 224)):  # Use 224x224 for ResNet50
    h, w = img.shape[:2]
    max_dim = max(h, w)
    top = (max_dim - h) // 2
    bottom = max_dim - h - top
    left = (max_dim - w) // 2
    right = max_dim - w - left
    img_padded = cv2.copyMakeBorder(img, top, bottom, left, right, cv2.BORDER_CONSTANT, value=[255, 255, 255])
    img_resized = cv2.resize(img_padded, target_size)
    return preprocess_input(img_resized.astype(np.float32))

# Enhanced Data Augmentation
aug_gen = ImageDataGenerator(
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    brightness_range=[0.8, 1.2],    # Added brightness adjustment
    channel_shift_range=10.0,       # Enhanced contrast
    fill_mode="nearest"
)

# Load images
X, y, labels = [], [], []
class_names = sorted(os.listdir(dataset_path))

for class_index, class_name in enumerate(class_names):
    class_path = os.path.join(dataset_path, class_name)
    if os.path.isdir(class_path):
        for img_name in os.listdir(class_path):
            img_path = os.path.join(class_path, img_name)
            img = cv2.imread(img_path)
            if img is not None:
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                img = pad_and_resize(img)
                X.append(img)
                y.append(class_index)
                labels.append(class_name)

X = np.array(X, dtype=np.float32)
y = np.array(y)
y = to_categorical(y, num_classes=len(class_names))

# Compute Class Weights
class_weights = compute_class_weight("balanced", classes=np.unique(y.argmax(axis=1)), y=y.argmax(axis=1))
class_weights = {i: weight for i, weight in enumerate(class_weights)}

# Augment Dataset
augmented_images, augmented_labels = [], []
for i in range(len(X)):
    img = X[i].reshape((1,) + X[i].shape)
    label = y[i]
    count = 0
    for batch in aug_gen.flow(img, batch_size=1):
        augmented_images.append(batch[0])
        augmented_labels.append(label)
        count += 1
        if count >= 4:  # Increased augmentation samples per image
            break

X_aug = np.array(augmented_images, dtype=np.float32)
y_aug = np.array(augmented_labels)

# Combine Original and Augmented Data
X_combined = np.concatenate((X, X_aug), axis=0)
y_combined = np.concatenate((y, y_aug), axis=0)

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X_combined, y_combined, test_size=0.2, random_state=42)

# Load ResNet50 (instead of EfficientNetB5)
base_model = ResNet50(weights="imagenet", include_top=False, input_shape=(224, 224, 3))  # Change to ResNet50

# Freeze Pretrained Layers Initially
for layer in base_model.layers:
    layer.trainable = False

# Model Architecture
x = GlobalAveragePooling2D()(base_model.output)
x = BatchNormalization()(x)
x = LayerNormalization()(x)   # Added Layer Normalization
x = Dense(512, activation="relu")(x)  # Increased neurons for better learning capacity
x = Dropout(0.4)(x)
x = Dense(256, activation="relu")(x)
x = Dropout(0.5)(x)
output = Dense(len(class_names), activation="softmax")(x)

model = Model(inputs=base_model.input, outputs=output)
model.compile(optimizer=Adam(learning_rate=1e-4), loss="categorical_crossentropy", metrics=["accuracy"])

# Callbacks
callbacks = [
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=4, min_lr=1e-6, verbose=1),
    EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True, verbose=1)
]

# Train Model
history = model.fit(
    X_train, y_train,
    epochs=35,  # Increased epochs for better learning
    batch_size=16,  # Reduced batch size for improved convergence
    validation_data=(X_test, y_test),
    class_weight=class_weights,
    callbacks=callbacks
)


# Prediction Function
def predict_shade(image_path):
    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = pad_and_resize(img)
    img = np.expand_dims(img, axis=0)
    prediction = model.predict(img)
    predicted_class = class_names[np.argmax(prediction)]
    print(f"Predicted Shade: {predicted_class}")
    return predicted_class

# Test Prediction
test_image_path = "/content/drive/MyDrive/Dataset/4M_1/4.jpg"
predicted_shade = predict_shade(test_image_path)

# Save the model in the current Colab environment
model.save('prediction.h5')

# Now, download the model file to your local machine
from google.colab import files
files.download('prediction.h5')

# Set up the models and evaluate their accuracy

# Evaluate ResNet50 model (Already trained model from your previous code)
resnet_loss, resnet_accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"ResNet50 - Loss: {resnet_loss:.4f}, Accuracy: {resnet_accuracy:.4f}")

# Evaluate EfficientNetB5 model (Already trained model from your previous code)
# Assuming the EfficientNetB5 model is saved in the variable `model` and trained as per your code above
efficientnet_loss, efficientnet_accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"EfficientNetB5 - Loss: {efficientnet_loss:.4f}, Accuracy: {efficientnet_accuracy:.4f}")

# Now create a simple comparison table to visualize the results
import pandas as pd

# Create a DataFrame for comparison
comparison_df = pd.DataFrame({
    "Model": ["ResNet50", "EfficientNetB5"],
    "Loss": [resnet_loss, efficientnet_loss],
    "Accuracy": [resnet_accuracy, efficientnet_accuracy]
})

# Display the comparison
print(comparison_df)

# Optionally, visualize the accuracy of both models using a bar plot
import matplotlib.pyplot as plt

# Plot accuracy comparison
plt.figure(figsize=(8, 6))
plt.bar(comparison_df["Model"], comparison_df["Accuracy"], color=['blue', 'orange'])
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.ylim([0, 1])
plt.show()

# Optionally, visualize the loss of both models using a bar plot
plt.figure(figsize=(8, 6))
plt.bar(comparison_df["Model"], comparison_df["Loss"], color=['blue', 'orange'])
plt.title("Model Loss Comparison")
plt.ylabel("Loss")
plt.show()